### ISSUE TITLE
torshify client does not work with Spotify Free account

### ISSUE THREAD

**Issue by ghost** [torshy/torshify-client#1]
here the reults of the Torshify.log

20 Mar 2012 07:38 [EventLoop] INFO  Torshify - [Medium] 06:38:46.820 I [offline_authorizer.cpp:279] Unable to login offline: no such user
20 Mar 2012 07:38 [EventLoop] INFO  Torshify - [Medium] 06:38:46.839 I [ap:1751] Connecting to AP A4.spotify.com:4070
20 Mar 2012 07:38 [EventLoop] INFO  Torshify - [Medium] 06:38:51.843 E [ap:1689] AP Socket Error: Undefined Error 0x4E20 (20000)
20 Mar 2012 07:38 [EventLoop] INFO  Torshify - [Medium] 06:38:51.843 E [ap:3901] Connection error:  117
20 Mar 2012 07:38 [EventLoop] INFO  Torshify - [Medium] 06:38:51.843 I [ap:1751] Connecting to AP A1.spotify.com:80
20 Mar 2012 07:38 [EventLoop] INFO  Torshify - [Medium] 06:38:51.911 I [ap:1209] Connected to AP: 78.31.12.95:80
20 Mar 2012 07:39 [EventLoop] INFO  Torshify - [Medium] 06:39:01.906 E [ap:3901] Connection error:  116
20 Mar 2012 07:39 [EventLoop] INFO  Torshify - [Medium] 06:39:01.906 I [ap:1751] Connecting to AP A3.spotify.com:443
20 Mar 2012 07:39 [EventLoop] INFO  Torshify - [Medium] 06:39:01.969 I [ap:1209] Connected to AP: 78.31.12.101:443
20 Mar 2012 07:39 [EventLoop] INFO  Torshify - [Medium] 06:39:02.660 E [ap:3901] Connection error:  409
20 Mar 2012 07:39 [EventLoop] INFO  Torshify - [Low] Logged in - UserNeedsPremium[Needs a premium account]
20 Mar 2012 07:39 [EventLoop] INFO  Torshify - [Low] Logged out

**Comment by torshy** [comment]
libspotify only works with Spotify Premium accounts I'm afraid. Try my r4dio app instead, it has Grooveshark integration which works without any account at all :)

**Comment by mediaexplorer74** [comment]
> libspotify only works with Spotify Premium accounts I'm afraid. Try my r4dio app instead, it has Grooveshark integration which works without any account at all :)

Hi (from 2022 year)). How are you? No plans to port your Torshify onto UWP ? ;)

**Comment by torshy** [comment]
Hi :) 

Does this thing still work? Spotify deprecated the native library many years ago and I must admit I haven't kept me updated on this thing. So I guess my answer is, no i have no immediate plans to port it.
